DROP TABLE IF EXISTS
    mpa,
    films,
    genres,
    films_genre,
    users,
    users_friends,
    favorite_films;

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name CHARACTER VARYING (200) NOT NULL,
    description CHARACTER VARYING (200),
    releasedate DATE NOT NULL,
    duration INTEGER NOT NULL,
    mpa_id INTEGER NOT NULL,
    rate INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT films_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.MPA (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name CHARACTER VARYING (200) NOT NULL,
    description CHARACTER VARYING (200) NOT NULL,
    CONSTRAINT film_mpa_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.GENRES (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name CHARACTER VARYING (200) NOT NULL,
    CONSTRAINT film_genres_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS_GENRES (
    film_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
    id INTEGER NOT NULL AUTO_INCREMENT,
    email CHARACTER VARYING (200) NOT NULL,
    login CHARACTER VARYING (200) NOT NULL,
    name CHARACTER VARYING (200) NOT NULL,
    birthday DATE NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USERS_FRIENDS (
     user_id INTEGER NOT NULL,
     friend_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.FAVORITE_FILMS (
     film_id INTEGER NOT NULL,
     user_id INTEGER NOT NULL
);